services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=
    volumes:
      - ./data:/app/data
    network_mode: host
